/**
 * Five Nights at Freddy's 1 -- Recompilation
 * TextRenderer.cpp: bitmap-font text via the embedded atlas + SpriteBatch.
 *
 * See TextRenderer.h for the design. Glyph cells are 16x16 px, advance 10 px,
 * ASCII 32..126 -- see include/font_atlas.h (generated by
 * scripts/gen_font_atlas.py from Liberation Mono, do not edit by hand).
 */

#include "TextRenderer.h"
#include "SpriteBatch.h"
#include "font_atlas.h"
#include <cstdarg>
#include <cstring>
#include <cstdio>

#if defined(_XBOX) || defined(_XBOX360) || defined(_M_PPCBE)
#include <xtl.h>
#include <d3d9.h>
#include <d3dx9.h>
#else
#error "Only Xbox 360 target supported"
#endif

namespace fnaf {

TextRenderer::TextRenderer()
    : m_device(0)
    , m_fontTexture(0)
    , m_batch(0)
    , m_scale(1.0f)
    , m_initialized(false)
{
    m_fmtBuf[0] = '\0';
}

TextRenderer::~TextRenderer()
{
    Shutdown();
}

bool TextRenderer::Init(void* device, SpriteBatch* batch, i32 heightPx)
{
    if (m_initialized) return true;
    if (!device || !batch || !batch->IsReady()) return false;

    m_device = device;
    m_batch  = batch;

    // Decode the embedded RGBA PNG atlas into a D3D texture.
    // D3DXCreateTextureFromFileInMemoryEx: verified in the XDK d3dx9tex.h.
    // v2.3: XDK docs say the Pool parameter of D3DXCreateTexture* is
    // "Unused; use 0" on Xbox 360 (resource pools are a PC concept).
    IDirect3DTexture9* tex = 0;
    HRESULT hr = D3DXCreateTextureFromFileInMemoryEx(
        (D3DDeviceX*)device,
        g_fontAtlasPng,
        (UINT)FONT_ATLAS_PNG_SIZE,
        FONT_ATLAS_COLS * FONT_ATLAS_CELL,   // width  (use D3DX_DEFAULT? explicit is safer)
        FONT_ATLAS_ROWS * FONT_ATLAS_CELL,   // height
        1,                                   // mip levels
        0,                                   // usage
        D3DFMT_A8R8G8B8,                     // keep RGBA
        (D3DPOOL)0,                        // pool: unused on 360, documented as "use 0"
        D3DX_FILTER_NONE,                    // 1:1 upload, no resize
        D3DX_FILTER_NONE,
        0,                                   // no color key (alpha comes from PNG)
        NULL, NULL,
        &tex);
    if (FAILED(hr) || !tex) {
        m_batch = 0;
        return false;
    }
    m_fontTexture = tex;

    m_scale = (float)heightPx / (float)FONT_ATLAS_CELL;
    if (m_scale < 0.5f) m_scale = 0.5f;
    if (m_scale > 4.0f) m_scale = 4.0f;

    m_initialized = true;
    return true;
}

void TextRenderer::Shutdown()
{
    if (m_fontTexture) {
        ((IDirect3DTexture9*)m_fontTexture)->Release();
        m_fontTexture = 0;
    }
    m_device = 0;
    m_batch = 0;
    m_initialized = false;
}

void TextRenderer::DrawText(i32 x, i32 y, const char* text, u32 color)
{
    if (!m_initialized || !m_batch || !text || !text[0]) return;

    const float cell   = (float)FONT_ATLAS_CELL * m_scale;
    const float adv    = (float)FONT_ATLAS_ADVANCE * m_scale;
    const float invColW = 1.0f / (float)(FONT_ATLAS_COLS * FONT_ATLAS_CELL);
    const float invColH = 1.0f / (float)(FONT_ATLAS_ROWS * FONT_ATLAS_CELL);

    float fx = (float)x;
    const float fy = (float)y;

    for (const char* p = text; *p; ++p) {
        const unsigned char c = (unsigned char)*p;
        if (c == '\n') { fx = (float)x; continue; }   // single-line API; skip
        if (c < FONT_ATLAS_FIRST || c >= FONT_ATLAS_FIRST + FONT_ATLAS_COUNT) {
            fx += adv;                                 // unknown char: advance only
            continue;
        }
        const int idx = c - FONT_ATLAS_FIRST;
        const int col = idx % FONT_ATLAS_COLS;
        const int row = idx / FONT_ATLAS_COLS;
        const float u0 = (float)(col * FONT_ATLAS_CELL) * invColW;
        const float v0 = (float)(row * FONT_ATLAS_CELL) * invColH;
        const float u1 = u0 + (float)FONT_ATLAS_CELL * invColW;
        const float v1 = v0 + (float)FONT_ATLAS_CELL * invColH;

        m_batch->Draw(m_fontTexture, fx, fy, cell, cell, u0, v0, u1, v1, color);
        fx += adv;
    }
}

void TextRenderer::DrawTextf(i32 x, i32 y, u32 color, const char* fmt, ...)
{
    if (!m_initialized || !fmt) return;

    va_list args;
    va_start(args, fmt);
    vsnprintf(m_fmtBuf, sizeof(m_fmtBuf) - 1, fmt, args);
    m_fmtBuf[sizeof(m_fmtBuf) - 1] = '\0';
    va_end(args);
    DrawText(x, y, m_fmtBuf, color);
}

i32 TextRenderer::MeasureText(const char* text) const
{
    if (!text) return 0;
    return (i32)((float)strlen(text) * (float)FONT_ATLAS_ADVANCE * m_scale);
}

void TextRenderer::DrawTextCentered(i32 y, const char* text, u32 color, i32 screenWidth)
{
    if (!m_initialized || !text || !text[0]) return;
    const i32 x = (screenWidth - MeasureText(text)) / 2;
    DrawText(x < 0 ? 0 : x, y, text, color);
}

void TextRenderer::DrawTextCenteredXY(i32 cx, i32 cy, const char* text, u32 color)
{
    if (!m_initialized || !text || !text[0]) return;
    const i32 x = cx - MeasureText(text) / 2;
    const i32 y = cy - (i32)((float)FONT_ATLAS_CELL * m_scale * 0.5f);
    DrawText(x, y, text, color);
}

} // namespace fnaf
