#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Regenerate include/font_atlas.h — the 160x160 monochrome bitmap font atlas used
by TextRenderer (white glyphs on transparent, 10x10 grid of 16x16 cells, ASCII
32..126, fixed advance 10 px).

Usage:
    python3 gen_font_atlas.py <font.ttf> [font_size] [--out font_atlas.h]

Default DNS size is chosen so glyphs fit the 16px cell.
"""
import sys, io, os
from PIL import Image, ImageDraw, ImageFont

CELL = 16
COLS = 10
ROWS = 10
ADVANCE = 10
FIRST = 32
COUNT = 95
SIZE = CELL * COLS  # 160


def build_atlas(ttf_path, font_size):
    font = ImageFont.truetype(ttf_path, font_size)
    ascent, descent = font.getmetrics()
    # Consistent BASELINE inside every 16px cell (bbox-centering made glyphs
    # "dance" vertically). Leave a 2px descender gap at the bottom.
    baseline = CELL - descent - 2
    if baseline - ascent < 0:
        baseline = ascent + 1

    atlas = Image.new("RGBA", (SIZE, SIZE), (0, 0, 0, 0))
    d = ImageDraw.Draw(atlas)

    for i in range(COUNT):
        ch = chr(FIRST + i)
        if ch == ' ':
            continue
        col, row = i % COLS, i // COLS
        x0 = col * CELL
        adv = font.getlength(ch)          # advance (constant for monospace)
        x = x0 + (CELL - adv) / 2.0       # center horizontally
        y = row * CELL + baseline
        # "ls" = left-baseline -> every glyph's baseline sits on the same line.
        d.text((x, y), ch, font=font, fill=(255, 255, 255, 255), anchor="ls")

    return atlas


def emit_header(png_bytes, out_path):
    lines = []
    lines.append("/**")
    lines.append(" * font_atlas.h -- generated by scripts/gen_font_atlas.py, do not edit.")
    lines.append(" *")
    lines.append(" * 160x160 RGBA PNG, white glyphs on transparent background:")
    lines.append(" *   - 10 x 10 grid of 16x16 cells")
    lines.append(" *   - ASCII 32..126 (95 printable chars), fixed advance %d px" % ADVANCE)
    lines.append(" *   - decoded at runtime via D3DXCreateTextureFromFileInMemoryEx")
    lines.append(" *     (verified present in the Xbox 360 XDK d3dx9tex.h)")
    lines.append(" */")
    lines.append("#pragma once")
    lines.append("")
    lines.append("#include <basetsd.h>")
    lines.append("")
    lines.append("#define FONT_ATLAS_CELL     %d" % CELL)
    lines.append("#define FONT_ATLAS_ADVANCE  %d" % ADVANCE)
    lines.append("#define FONT_ATLAS_COLS     %d" % COLS)
    lines.append("#define FONT_ATLAS_ROWS     %d" % ROWS)
    lines.append("#define FONT_ATLAS_FIRST    %d" % FIRST)
    lines.append("#define FONT_ATLAS_COUNT    %d" % COUNT)
    lines.append("#define FONT_ATLAS_PNG_SIZE %d" % len(png_bytes))
    lines.append("")
    lines.append("static const unsigned char g_fontAtlasPng[FONT_ATLAS_PNG_SIZE] = {")
    for pos in range(0, len(png_bytes), 16):
        chunk = png_bytes[pos:pos + 16]
        hexs = ", ".join("0x%02X" % b for b in chunk)
        lines.append("    %s," % hexs)
    lines.append("};")
    lines.append("")
    open(out_path, "w").write("\n".join(lines))
    print("wrote %s (%d bytes, %d glyphs)" % (out_path, len(png_bytes), COUNT))


def main():
    if len(sys.argv) < 2:
        sys.exit("usage: gen_font_atlas.py <font.ttf> [size] [--out header]")
    ttf = sys.argv[1]
    size = 14
    out = "include/font_atlas.h"
    rest = sys.argv[2:]
    while rest:
        a = rest.pop(0)
        if a == "--out":
            out = rest.pop(0)
        elif a.isdigit():
            size = int(a)
    atlas = build_atlas(ttf, size)
    buf = io.BytesIO()
    atlas.save(buf, format="PNG", optimize=True)
    emit_header(buf.getvalue(), out)


if __name__ == "__main__":
    main()