#pragma once

// ============================================================================
//  asset_mapping.h — SEMANTIC MASTER ASSET MAPPER (all games)
//  ---------------------------------------------------------------------------
//  Game code refers to assets by MEANING, never by a magic "img_NNN" number.
//  Every constant resolves to a pak texture name (the strings PakLoader::
//  FindTexture takes). One sub-namespace per game; a module uses only its
//  own section, so new games plug in here without collisions:
//
//    fnaf_asset   — FNAF 1  (FNaF1Module)            <- filled, in use
//    fnaf2_asset  — FNAF 2  (FNaF2Module, stage 6)
//    fnaf3_asset  — FNAF 3  (FNaF3Module, stage 7)
//    fnaf4_asset  — FNAF 4  (stage 8)
//    sl_asset     — Sister Location (stage 9)
//
//  Ground truth for every value lives in include/assets/asset_mapping_<id>.hpp
//  (generated by ctfak-cpp "Recomp Pack": {index, filename, w, h, alpha} per
//  handle) plus the frame-layout evidence in docs/. Handles are resolved from
//  the frame object tables (object name -> starting image) and verified
//  visually.
//
//  VS2010/C++03: plain `static const char* const` (internal linkage) — the
//  C++17 `inline` variable form does NOT compile on the XDK toolchain.
// ============================================================================

namespace fnaf_asset {

// ---- FNAF 1 ---------------------------------------------------------------
// Identity provenance (office/title frame object tables, visual check):
//   OFFICE_BG      — object "Active 3", frame "Frame 1", placed at (0,0)
//   MENU_BG        — object "Active 2", frame "title", placed at (0,0)
//   CAM_MONITOR_BG — object "frame", layer 2 of the office frame
//   DOOR_BUTTON    — objects "door open left/right", "light on left/right"
//   CAM_MAP        — object "Active 9" (floor plan with the YOU marker)
static const char* const MENU_BG         = "img_431"; // title screen, 1280x720
static const char* const OFFICE_BG       = "img_39";  // office parallax bg, 1600x720
static const char* const CAM_MONITOR_BG  = "img_11";  // monitor frame, 1280x720
static const char* const CAM_STATIC      = "img_18";  // video static overlay, 1280x720
static const char* const CAM_MAP         = "img_164"; // camera floor plan, 400x400
static const char* const OFFICE_LIGHTS   = "img_608"; // Halloween string lights, 1600x253 (NOT a door-light glow!)
static const char* const LEFT_DOOR       = "img_103"; // left door, 223x720
static const char* const RIGHT_DOOR      = "img_119"; // right door, 248x720
static const char* const DOOR_BUTTON     = "img_129"; // door/light button, 62x120
static const char* const MAP_BUTTON      = "img_167"; // cam map button, 60x40
static const char* const MAP_ICON        = "img_170"; // cam map location icon, 31x25
static const char* const MUTE_CALL       = "img_481"; // mute call button, 121x31
static const char* const FREDDY_PORTRAIT = "img_573"; // "yellow bear" poster, 541x521
static const char* const FLIP_UP_BAR     = "img_156"; // monitor flip-up strip, 792x82
static const char* const FLIP_DOWN_BAR   = "img_162"; // monitor flip-down strip, 1070x82

} // namespace fnaf_asset

// ---- FNAF 2 (stage 6) ------------------------------------------------------
// namespace fnaf2_asset { ... } — fill from the FNAF2 dump
// (build/Dumps/Five Nights at Freddys 2: office = "Frame 1" 1600x768,
//  751 groups; cameras via the "viewing" counter + "lit?" flashlight).

// ---- Sister Location (stage 9) --------------------------------------------
// namespace sl_asset { ... } — fill from the SL dump (per-room frames:
// Elevator, Ballora Gallery, Funtime Auditorium, ...; pak 1.5 GB, streaming).
